### ISSUE TITLE
publish to npm?

### ISSUE THREAD

**Issue by spudly** [olahol/scrollparent.js#1]
This looks like a really useful module, and it looks as if it was created to be used with node, but for some reason it's not published to npm.

Would you be willing to publish this to npm?

**Comment by olahol** [comment]
You are absolutely right that it should be published to npm, I will do so in a moment.

**Comment by olahol** [comment]
Fixed in `eab407a21731ff9a33daa1f76491c647c13565d1`.

https://www.npmjs.com/package/scrollparent

**Comment by spudly** [comment]
Sweet, thanks!
