### ISSUE TITLE
IE 11 scroll parent gives wrong node for window

### ISSUE THREAD

**Issue by AndyOGo** [olahol/scrollparent.js#6]
If the scroll parent is the highest in IE11 it should the root `<html>` node not the `<body>` node.

**Edit**
http://stackoverflow.com/questions/2717252/document-body-scrolltop-is-always-0-in-ie-even-when-scrolling
http://stackoverflow.com/questions/6736849/scrolltop-not-working-in-ie

**Comment by olahol** [comment]
This is now fixed in version `2.0.0` as the root element has been changed to `document.scrollingElement || document.htmlElement`. Thanks for the the feedback @AndyOGo.
